
spring:
  jpa:
    hibernate:
      ddl-alto: update
  datasource:
    url: jdbc:mysql://localhost:3307/mercadolivro?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
  jackson:
    default-property-inclusion: non_null


    #JPA configuration
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.show-sql=true
#    spring.jpa.generate-ddl=true
#    spring.jpa.properties.hibernate.format_sql=true
